sudo: required

env:
  global:
    - VERSION_NUMBER="0.6.$TRAVIS_BUILD_NUMBER"

services:
  - docker

language: csharp
mono: none
solution: MockItUp.sln
dotnet: 3.1
install:
  - dotnet restore

script:
  - dotnet build --configuration Release -p:Version=$VERSION_NUMBER
  - dotnet test test/MockItUp.UnitTest/MockItUp.UnitTest.csproj
  - docker-compose up --build --abort-on-container-exit --exit-code-from integrationtest

after_success:
  - ./deploy.sh
    
#notifications:
#  email:
#    on_failure: always
#    on_success: never