sudo: required

env:
  global:
    - VERSION_NUMBER="0.6.$TRAVIS_BUILD_NUMBER"

services:
  - docker

language: csharp
mono: none
solution: MockItUp.sln
dotnet: 3.1
install:
  - dotnet restore

script:
  - dotnet build --configuration Release -p:Version=$VERSION_NUMBER
  - dotnet test test/MockItUp.UnitTest/MockItUp.UnitTest.csproj
  - docker-compose up --build --abort-on-container-exit --exit-code-from integrationtest

deploy:
  - docker build -t edentidus/mockitup:v$VERSION_NUMBER -f ./src/MockItUp.Console/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push edentidus/mockitup:v$VERSION_NUMBER
  - dotnet nuget push src/MockItUp.Client\bin\Release\MockItUp.Client.$VERSION_NUMBER.nupkg --api-key $NUGET_KEY --source https://api/nuget.org/v3/index.json

stages:
  - name: deploy
    if: branch = main
    
#notifications:
#  email:
#    on_failure: always
#    on_success: never