version: '3'

services:
  mockserver:
    build:
      context: ./src
      dockerfile: MockItUp.Console/Dockerfile
    environment:
      - SETTING_FILE=/etc/mockitup.d/conf.yml
    ports:
      - 5000:5000
      - 5010:5010
    volumes:
      - ./test/MockItUp.IntegrationTest/mockitup.d:/etc/mockitup.d
      
  integrationtest:
    build:
      context: ./test
      dockerfile: MockItUp.IntegrationTest/Dockerfile
    environment:
      - SERVICE_ORDER=http://mockserver:5000
      - SERVICE_SHIPMENT=http://mockserver:5010
    depends_on:
      - mockserver
