version: '3'

services:
  mockserver:
    build:
      context: ./src
      dockerfile: MockItUp.Console/Dockerfile
    environment:
      - SETTING_FILE=/etc/mockitup.d/conf.yml
    expose:
      - 5000
      - 5010
    ports:
      - 5000:5000
      - 5010:5010
    volumes:
      - ./test/mockitup.d:/etc/mockitup.d
